"""empty message

Revision ID: f56e6162b5a3
Revises: 
Create Date: 2020-11-21 14:55:50.455438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56e6162b5a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image_dir', sa.String(length=100), nullable=False),
    sa.Column('effect', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.String(length=100), nullable=False),
    sa.Column('validity', sa.String(length=100), nullable=False),
    sa.Column('camera', sa.Boolean(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=100), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('schedules_common',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=100), nullable=False),
    sa.Column('startdate', sa.String(length=100), nullable=False),
    sa.Column('enddate', sa.String(length=100), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_medicines',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('medicines_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medicines_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], )
    )
    op.create_table('schedules_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('check', sa.Boolean(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('schedules_common_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedules_common_id'], ['schedules_common.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules_medicines',
    sa.Column('schedules_common_id', sa.Integer(), nullable=True),
    sa.Column('medicines_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medicines_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['schedules_common_id'], ['schedules_common.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules_medicines')
    op.drop_table('schedules_date')
    op.drop_table('users_medicines')
    op.drop_table('schedules_common')
    op.drop_table('users')
    op.drop_table('medicines')
    # ### end Alembic commands ###
